apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-wrkh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-wrkh
    app.kubernetes.io/part-of: test-app-416
  name: test-component-wrkh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-no-dockerfile
      app.kubernetes.io/instance: test-component-wrkh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-no-dockerfile
        app.kubernetes.io/instance: test-component-wrkh
    spec:
      containers:
      - image: nodejs-no-dockerfile:latest
        name: nodejs-no-dockerfile
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
status: {}
