apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-kjeq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-kjeq
    app.kubernetes.io/part-of: test-app-416
  name: test-component-kjeq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: maven-hello-world
      app.kubernetes.io/instance: test-component-kjeq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maven-hello-world
        app.kubernetes.io/instance: test-component-kjeq
    spec:
      containers:
      - image: maven-hello-world:latest
        name: maven-hello-world
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
status: {}
